name: Environment Variables
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: chekcout repo
        uses: actions/checkout@v2
      - name: run python script
        run: python hello.py
  Build:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: chekcout repo
        uses: actions/checkout@v2
      - name: build artifact
        uses: actions/upload-artifact@v2.2.4  

   



